# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8fed39972e2cae278a61172fd25e9c29dc4da72c3d7d47d7f8523154a116f33c22578ca2aa8a21ec65ceb44c158a8564d7abe65cad1ceee68e5a66490225497

test:
  secret_key_base: a48eb1e66e19c55b830b41eec2b15b5f56a8f1eeaddace530aa5055aa14494c63116e93e53844e6120ef39f779bfe00872832aed9eceae75c84d7bca5b7a6939

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
